config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get "members/new_user" => "registrations#new_user", as: "new_user" # custom path to sign_up/registration
    get "members/new_student" => "registrations#new_student", as: "new_student"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :categories
  resources :informations
  resources :member
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/adviser.rb
class Adviser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :title
  validates_uniqueness_of :title, case_sensitive: false
end

app/models/content.rb
class Content < ActiveRecord::Base
  validates_presence_of :slug, :body
end

app/models/member.rb
class Member < User
end

app/models/student.rb
class Student < User
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :skip_password_validation
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  def is_member?
    return self.type == 'Member'
  end

  def is_student?
    return self.type == 'Student'
  end
  protected

  def password_required?
    return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = get_category
    @home_events = (Content.find_by slug: 'home_event') if @category.title == 'Vietnam Bussiness Club'
    @about_vietnam = Content.find_by slug: 'about_vietnam'
    @vfsc_contents = (Content.where slug: 'vfsc_contents') if @category.title == 'Vietnam Foreign Student Club'
  end

  private

  def get_category
    Category.find params['id']
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home_events = Content.find_by slug: 'home_event'
    @about_vietnam = Content.find_by slug: 'about_vietnam'
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  def new
    super
  end

  def new_user
    @resource = Member.new
  end

  def new_student
    @resource = Student.new
  end

  def create
    # add custom create logic here
    @resource = build_resource(sign_up_params)
    if params['user']['school_year'].nil?
      @resource.becomes!(Member)
    else
      @resource.becomes!(Student)
    end
    # build_resource(sign_up_params)
    @resource.save
    yield resource if block_given?
    if @resource.persisted?
      if @resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        # sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(@resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(@resource)
      end
    else
      # clean_up_passwords resource
      # set_minimum_password_length
      # respond_with resource
      render :new_user
    end
  end

  def resource
    @resource ||= User.new
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email, :register_date, :invoice, :enterprise_name, :address, :full_name, :position, :department, :tel, :fax, :url, :other, :gender, :birthday, :school_name, :education, :vocal, :school_year)
    end
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_about_us.slim
#category-show-about-us
  .row
    .col-sm-8
      table.table.table-hover.table-striped
        tr
          td 社名
          td 一般社団法人VietnamClub
        tr
          td 代表者
          td 村上福壽郎
        tr
          td 所在地
          td 大阪市旭区高殿六丁目1番22号グローバル人材育成センター内
        tr
          td 設立
          td 平成28年8月23日
        tr
          td 理事
          td 
            | 村上福壽郎
            br
            | 柳澤一生
        tr
          td 名誉会長
          td チャン・ドゥック・ビン総領事
      .col-sm-12
        p
          .col-sm-12
            h1 ご挨拶
        p
          = image_tag '13.png', class: 'main-image'
        p 当社団は大きく３つの交流を目的に今年に発足された団体です。
        p １つ目はベトナムと日本の文化の交流。
        p ２つ目はベトナム企業と日本企業の経済の交流。
        p 最後にベトナム人留学生と日本企業の人材の交流。
        p これら３つの交流について在大阪ベトナム社会主義共和国総領事館のチャン・ドック・ビン総領事を名誉会長にお迎えして行う活動のために設立されました。
        p 当社団の活動は、「ベトナムビジネス倶楽部」と「ベトナム留学生倶楽部」の二本柱で活動させて頂きます。
        p 「ベトナムビジネス倶楽部」では、日本国内のビジネスから飛躍して、海外進出を模索する企業様へ向けて「海外進出超基礎セミナー」を開催致します。ベトナム進出への道のりが理解できるものと考えており す。
        p また、「ベトナム留学生倶楽部」では、在大阪ベトナム青年学生協会の留学生や若手の方々と共に、日本企業の文化を知り、日本で働くためのノウハウを蓄積する活動を企画してまいります。
        p ベトナムと日本の交流という大きな目的を持って活動しておりますが、幣社団だけで、すべてを行えるとは考えておりません。
        p 多くの方々のご理解とご協力があってこそ、この大きな目的が達成されます。
        p 当社団の趣旨にご理解いただき、一緒に活動してくれる仲間が集まることを願いご挨拶とさせて頂きます。
    .col-sm-4
      = render 'shared/advertise'

app/views/categories/_register.slim
#category-show-register
  .row
    .col-sm-8
      a.btn-primary href="#{new_user_path}"
        .well.well-lg.text-center.background-inherit
          h3 賛助会員
          h3 入会のご案内
      p
        | 一般社団法人VietnamCLubは、ベトナム留学生と日本企業との人材交流、ベトナム企業と日本企業の経済交流を通じて、両国間の友好関係の発展に寄与するため、2016年8月に発足いたしました。
        br
        | ベトナムと日本の交流という大きな目的を持って活動しておりますが、幣社団だけで、すべてを行えるとは考えておりません。多くの方々のご理解とご協力があってこそ、両国間の交流が達成されるものと考えております。この目的に賛同し、両国の発展にご尽力いただける方（個人・事業者・団体）を賛助会員として募集しています。

      br
      br
      a.btn-danger href="#{new_student_path}"
        .well.well-lg.text-center.background-inherit
          h3 学生会員
          h3 入会のご案内
      p 般社団法人VietnamClubは、ベトナム留学生と日本企業との人材交流、ベトナム企業と日本企業の経済交流を通じて、両国間の友好関係の発展に寄与するため、2016年8月に発足いたしました。両国の発展にご尽力いただける方（個人・事業者・団体）を賛助会員として募集している同時、無料会員としてベトナム人留学生の皆さんの参加を歓迎しています。

      br
      br
      .btn-warning href="#"
        .well.well-lg.text-center.background-inherit
          h3 Adviser
          h3 募　　集
      p 
        | ベトナム及び近隣諸国でのお仕事の経験と知識をおかしください。ベトナム進出企業は勿論、こらから進出する企業、日本に来ている留学生も皆さまのご支援をまち望んでいます。
        br
        | まずは、VietnamClubにご連絡ください。
        br
        | TEL: 06(6956)4115
        br
        | Email: vnclub.j@gmail.com

      br
      br

    .col-sm-4
      = render 'shared/advertise'

app/views/categories/_vietnam_bussiness_club.slim
#category-show-vbc
  .row
    .col-sm-8
      .col-sm-6
        a.btn-primary data-target="#bussinessClub1" data-toggle="modal" type="button" 
          .well.well-lg.text-center.btn-primary.background-inherit
            h4「留学生」翻訳サービス
        /! Modal
        #bussinessClub1.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
          .modal-dialog role="document" 
            .modal-content
              .modal-header
                button.close aria-label="Close" data-dismiss="modal" type="button" 
                  span aria-hidden="true"  &times;
                h4#myModalLabel.modal-title
              .modal-body
                .panel.panel-primary
                  .panel-heading
                    h3.panel-title 「留学生」翻訳サービス
                  .panel-body
                    p= image_tag '8.png', class: 'width-100'
              .modal-footer
                button.btn.btn-default data-dismiss="modal" type="button" 閉じる
                a.btn.btn-default href="https://docs.google.com/forms/d/e/1FAIpQLSeqqHXNnOUZ-3GsnS5Ow3ZgI_qp9zjZFMfqjSFrjzoGSoJfoA/viewform" type="button" 問合せ
      .col-sm-6
        a.btn-primary data-target="#bussinessClub2" data-toggle="modal" type="button" 
          .well.well-lg.text-center.btn-primary.background-inherit
            h4「留学生」告知サービス
        /! Modal
        #bussinessClub2.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
          .modal-dialog role="document" 
            .modal-content
              .modal-header
                button.close aria-label="Close" data-dismiss="modal" type="button" 
                  span aria-hidden="true"  &times;
                h4#myModalLabel.modal-title 
              .modal-body
                .panel.panel-primary
                  .panel-heading
                    h3.panel-title「留学生」告知サービス
                  .panel-body
                    p= image_tag '9.png', class: 'width-100'
              .modal-footer
                button.btn.btn-default data-dismiss="modal" type="button" 閉じる
                a.btn.btn-default href="https://docs.google.com/forms/d/e/1FAIpQLSeqqHXNnOUZ-3GsnS5Ow3ZgI_qp9zjZFMfqjSFrjzoGSoJfoA/viewform" type="button" 問合せ
      .col-sm-6
        a.btn-primary data-target="#bussinessClub3" data-toggle="modal" type="button" 
          .well.well-lg.text-center.btn-primary.background-inherit
            h4 ベトナムの「今」お役立ち情報
        /! Modal
        #bussinessClub3.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
          .modal-dialog role="document" 
            .modal-content
              .modal-header
                button.close aria-label="Close" data-dismiss="modal" type="button" 
                  span aria-hidden="true"  &times;
                h4#myModalLabel.modal-title
              .modal-body
                - if @about_vietnam.present?
                  .panel.panel-primary
                    .panel-heading
                      h3.panel-title= @about_vietnam.title
                    .panel-body
                      p= simple_format @about_vietnam.body
              .modal-footer
                button.btn.btn-default data-dismiss="modal" type="button" 閉じる
                a.btn.btn-default href="https://docs.google.com/forms/d/e/1FAIpQLSeqqHXNnOUZ-3GsnS5Ow3ZgI_qp9zjZFMfqjSFrjzoGSoJfoA/viewform" type="button" 問合せ
      .col-sm-6
        a.btn-primary data-target="#bussinessClub4" data-toggle="modal" type="button" 
          .well.well-lg.text-center.btn-primary.background-inherit
            h4 よろずメール相談
        /! Modal
        #bussinessClub4.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
          .modal-dialog role="document" 
            .modal-content
              .modal-header
                button.close aria-label="Close" data-dismiss="modal" type="button" 
                  span aria-hidden="true"  &times;
                h4#myModalLabel.modal-title
              .modal-body
                .panel.panel-primary
                  .panel-heading
                    h3.panel-title よろずメール相談
                  .panel-body
                    p= image_tag '10.png', class: 'width-100'
              .modal-footer
                button.btn.btn-default data-dismiss="modal" type="button" 閉じる
                a.btn.btn-default href="https://docs.google.com/forms/d/e/1FAIpQLSeqqHXNnOUZ-3GsnS5Ow3ZgI_qp9zjZFMfqjSFrjzoGSoJfoA/viewform" type="button" 問合せ
      .col-sm-6
        a.btn-primary data-target="#bussinessClub5" data-toggle="modal" type="button" 
          .well.well-lg.text-center.btn-primary.background-inherit
            h4 Vietnam Discussion
        /! Modal
        #bussinessClub5.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
          .modal-dialog role="document" 
            .modal-content
              .modal-header
                button.close aria-label="Close" data-dismiss="modal" type="button" 
                  span aria-hidden="true"  &times;
                h4#myModalLabel.modal-title
              .modal-body
                .panel.panel-primary
                  .panel-heading
                    h3.panel-title Vietnam Discussion
                  .panel-body
                    p= image_tag '14.png', class: 'width-100'
                    p= image_tag '15.png', class: 'width-100'
              .modal-footer
                button.btn.btn-default data-dismiss="modal" type="button" 閉じる
                a.btn.btn-default href="https://docs.google.com/forms/d/e/1FAIpQLSeqqHXNnOUZ-3GsnS5Ow3ZgI_qp9zjZFMfqjSFrjzoGSoJfoA/viewform" type="button" 問合せ
    .col-sm-4
      = render 'shared/advertise'

app/views/categories/_vietnam_foreign_student_club.slim
#category-show-vbc
  .row
    .col-sm-8
      .col-sm-6
        a.btn-warning data-target="#bussinessClub1" data-toggle="modal" type="button" 
          .well.well-lg.text-center.btn-primary.background-inherit
            h4「留学生」翻訳サービス
        /! Modal
        #bussinessClub1.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
          .modal-dialog role="document" 
            .modal-content
              .modal-header
                button.close aria-label="Close" data-dismiss="modal" type="button" 
                  span aria-hidden="true"  &times;
                h4#myModalLabel.modal-title
              .modal-body
                .panel.panel-primary
                  .panel-heading
                    h3.panel-title「留学生」翻訳サービス
                  .panel-body
                    p= image_tag '8.png', class: 'width-100'
              .modal-footer
                button.btn.btn-default data-dismiss="modal" type="button" 閉じる
                a.btn.btn-default href="https://docs.google.com/forms/d/e/1FAIpQLSeqqHXNnOUZ-3GsnS5Ow3ZgI_qp9zjZFMfqjSFrjzoGSoJfoA/viewform" type="button" 問合せ
      .col-sm-6
        a.btn-warning data-target="#bussinessClub2" data-toggle="modal" type="button" 
          .well.well-lg.text-center.btn-primary.background-inherit
            h4「留学生」告知サービス
        /! Modal
        #bussinessClub2.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
          .modal-dialog role="document" 
            .modal-content
              .modal-header
                button.close aria-label="Close" data-dismiss="modal" type="button" 
                  span aria-hidden="true"  &times;
                h4#myModalLabel.modal-title 
              .modal-body
                .panel.panel-primary
                  .panel-heading
                    h3.panel-title「留学生」告知サービス
                  .panel-body
                    p= image_tag '9.png', class: 'width-100'
              .modal-footer
                button.btn.btn-default data-dismiss="modal" type="button" 閉じる
                a.btn.btn-default href="https://docs.google.com/forms/d/e/1FAIpQLSeqqHXNnOUZ-3GsnS5Ow3ZgI_qp9zjZFMfqjSFrjzoGSoJfoA/viewform" type="button" 問合せ
      - if @vfsc_contents.present? 
        - @vfsc_contents.order(id: :desc).each do |content|
          .col-sm-12
            .panel.panel-warning
              .panel-heading
                h3.panel-title= content.title
              .panel-body
                p= simple_format content.body
                - if content.title != "セミナー・イベント情報"
                  p 
                    a.btn.btn-default href="#{new_student_path}" 学生会員入会のご案内
    .col-sm-4
      = render 'shared/advertise'

app/views/categories/show.slim
- if @category.title == 'Vietnam Bussiness Club' 
  = render 'vietnam_bussiness_club'
- elsif @category.title == 'Vietnam Foreign Student Club' 
  = render 'vietnam_foreign_student_club'
- elsif @category.title == 'Adviser' 
  = render 'adviser'
- elsif @category.title == '会社概要' 
  = render 'about_us'
- elsif @category.title == '入会のご案内' 
  = render 'register'
  

app/views/home/index.slim
#home-index
  .row
    .col-sm-12
      #home-carousel.carousel.slide data-ride="carousel" 
        /! Indicators
        ol.carousel-indicators
          li.active data-slide-to="0" data-target="#chome-carousel" 
          li data-slide-to="1" data-target="#home-carousel" 
        /! Wrapper for slides
        .carousel-inner role="listbox" 
          .item.active
            =image_tag 'http://en.toureast.com/portals/0/img/country/japan/japan_header.jpg', class: 'width-100'
          .item
            =image_tag 'mu-cang-chai-crop.jpg', class: 'width-100'
        /! Controls
        a.left.carousel-control data-slide="prev" href="#home-carousel" role="button" 
          span.glyphicon.glyphicon-chevron-left aria-hidden="true" 
          span.sr-only Previous
        a.right.carousel-control data-slide="next" href="#home-carousel" role="button" 
          span.glyphicon.glyphicon-chevron-right aria-hidden="true" 
          span.sr-only Next
  .row
    .col-sm-8
      .panel.panel-default
        .panel-heading
          h3.panel-title Vietnam Club は
        .panel-body
          p 一般社団法人VietnamClubは、ベトナム留学生と日本企業との人材交流、ベトナム企業と日本企業の経済交流を通じて、両国間の友好関係の発展に寄与するため、2016年8月に発足いたしました。
          p ビジネスに役立つ情報発信や、在大阪ベトナム学生青年協会様にご協力頂きながら、留学生の方々に日本文化や習慣をご理解頂き、日本で働くためのノウハウを蓄積して頂く活動を行っています。
      .panel.panel-default
        .panel-heading
          h3.panel-title 応援団体
        .panel-body
          p Vietnam　clubでは、下記の団体を応援しています。
          p VYSA-OSAKA　在大阪ベトナム青年学生協会
          p 
            a href="http://vysa-osaka.org/" http://vysa-osaka.org/
          p 
            .fb-page data-adapt-container-width="true" data-hide-cover="false" data-href="https://www.facebook.com/VYSA.OSAKA/" data-show-facepile="true" data-small-header="false" data-tabs="timeline" 
              blockquote.fb-xfbml-parse-ignore cite="https://www.facebook.com/VYSA.OSAKA/" 
                a href="https://www.facebook.com/VYSA.OSAKA/"  VYSA-Osaka


      - if @home_events.present?
        .panel.panel-default
          .panel-heading
            h3.panel-title= @home_events.title
          .panel-body
            p= simple_format @home_events.body
      - if @about_vietnam.present?
        .panel.panel-default
          .panel-heading
            h3.panel-title= @about_vietnam.title
          .panel-body
            p= simple_format @about_vietnam.body
      .panel.panel-default
        .panel-heading
          h3.panel-title イベント情報
        .panel-body
          p ２０１７/２/２５　ベトナム留学生　就職支援セミナー　～先輩の声～
          p ２０１６/１２/８　ショートセミナー＆交流会
          p ２０１５/１０/8　ショートセミナー＆交流会
    .col-sm-4
      p= image_tag '7.png', class: 'width-100'
      = render 'shared/advertise'
      - cat = Category.where(title: '入会のご案内').last
      a.btn-primary href="#{category_path cat}"
        .well.well-lg.text-center.btn-primary.background-inherit
          h4 賛助会員
          h4 入会のご案内
      a.btn-success href="document/Vietnam-club-information.docx" download=""
        .well.well-lg.text-center.btn-success.background-inherit
          h4 バナー広告募集
          h5 留学生はベトナムに関心のある
          h5 企業との出会いを求めています

app/views/layouts/application.slim
doctype html
html
  head
    title Vietnam club
    meta name="viewport" content="width=1170, initial-scale=1, user-scalable=no"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800' rel='stylesheet' type='text/css'
    link href='https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/2.8.0/css/flag-icon.min.css' rel='stylesheet' type='text/css'
    
  body
    #fb-root
      javascript:
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9&appId=484507625050435";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

    .container-fluid
      .row
        #header
          .container
            = render 'shared/header'
            - if flash[:notice]
              .alert.alert-info= notice
            - if flash[:alert]
              .alert.alert-danger= alert
        #main-container
          .container
            = yield
        #footer
          .container
            = render 'shared/footer'

app/views/shared/_advertise.slim
.panel.panel-default
  .panel-body
    =image_tag 'vysa.jpg', class: 'width-100'
/ .panel.panel-default
/   .panel-heading
/     h3.panel-title ベトナムビジネス倶楽部
/   .panel-body
/     p ベトナム留学生　就職支援セミナー
/     p 仕事を探す
/ .panel.panel-default
/   .panel-heading
/     h3.panel-title アドバイザー
/   .panel-body
/     p Ａｄｖｉｓｅｒ

.mapouter
  .gmap_canvas
    iframe#gmap_canvas frameborder="0" height="370" marginheight="0" marginwidth="0" scrolling="no" src="https://maps.google.com/maps?q=Japan%2C%20%E3%80%92535-0031%20%C5%8Csaka-fu%2C%20%C5%8Csaka-shi%2C%20Asahi-ku%2C%20Takadono%2C%206%20Chome%E2%88%92%EF%BC%91%E2%88%9222&t=&z=14&ie=UTF8&iwloc=&output=embed" width="100%" 
    script src="http://www.embedgooglemap.net/mapscript.js"
  .hidden
    br embed google map by 
    a href="http://www.embedgooglemap.net" embedgooglemap.net

app/views/shared/_footer.slim
#footer
  .row
    .col-sm-4
      address
        h4 一般社団法人ＶｉｅｔｎａｍＣｌｕｂ
        p 〒535-0031
        p 大阪市旭区高殿6丁目1番22号
        p グローバル人材育成センター内
        p Tel 06(6956)4115
        p E-mail vnclub.j@gmail.com
    .col-sm-8.footer-buttons-group
      - Category.all.each do |cat|
        .button-wrap
          a.btn.btn-default href="#{category_path cat}" role="button"
            span= cat.title
    .col-sm-12.text-right
      small Copyright © 2016 ＶｉｅｔｎａｍＣｌｕｂ. All Rights Reserved.

app/views/shared/_header.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#{root_path}"
        =image_tag 'logo.png', class: 'width-100-px image-brand-header'
        span.brand-name-text 一般社団法人VietnamClub
    / #bs-example-navbar-collapse-1.collapse.navbar-collapse
    /   ul.nav.navbar-nav.navbar-right
    /     li
    /       a href="#" 
    /         span.flag-icon.flag-icon-jp
    /         | 日本語
    /     li
    /       a href="#" 
    /         span.flag-icon.flag-icon-vn
    /         | Tiếng việt
    /     li
    /       a href="#" 
    /         span.flag-icon.flag-icon-gb
    /         | English

nav.navbar.navbar-default.main-navbar
  .container-fluid
    .row
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          - Category.all.each do |cat|
            - status = (params['controller'] == 'categories' && params['action'] == 'show' && params['id'] == cat.id.to_s) ? 'active' : ''
            li class="#{status}"
              a href="#{category_path cat}"= cat.title